### ISSUE TITLE
unable to find module 'Step' when initializing minionpool

### ISSUE THREAD

**Issue by apveitas** [marcelog/rabbitmq_minionpool#2]
Line 4 in rabbitmq_minionpool.js is causing initializiation of the rabbitmq to blow up:

var Step = require('Step');

when initialzing our process we get the following error:

/usr/bin/node bin/device-report-gateway.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'Step'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/al/dev/client-projects/rabbitmq_minionpool/src/rabbitmq_minionpool.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home.......)

The code needs to be changed to

var Step = require('step');  // lowercase 'step' , not 'Step'

**Comment by marcelog** [comment]
fixed :) it's odd that i didn't have this issue, though.

thanks for the heads up!

**Comment by apveitas** [comment]
Not sure, but it might be related to the following.  What OS are you running for you dev env?

http://stackoverflow.com/questions/13617863/can-i-force-node-js-require-to-be-case-sensitive

**Comment by marcelog** [comment]
mm a mac, interesting.. so you can now update to 0.0.7, where this should be fixed
